z=zeros(1,21);
z(6)=1;
n = 0:20;
m = -5:15;
figure(1)
subplot(2,1,1);
stem(z,n);
title ('Reprezentare grafica in functie de n');
grid;
subplot(2,1,2);
stem(z,m);
title ('Reprezentare grafica in functie de m');
grid;
t=abs(10-n);
figure(2);
stem(t,n);
title ('Reprezentare grafica in functie de n');
grid;
figure(3);
p=-15:25;
x1= sin((pi/17)*p);
q=0:50;
x2=cos((pi/sqrt(23))*q);
plot(x1,p,x2,q);
grid;
figure(4);
subplot(2,1,1);
stem(x1,p);
title ('Reprezentare grafica in functie de p');
grid;
subplot(2,1,2);
stem(x2,q);
title ('Reprezentare grafica in functie de q');
grid;